
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresql
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresql/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.fits.cloud
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.fits.cloud
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
