apiVersion: v1
data:
  ENABLE_LEADER_ELECTION: {{ .Values.postgreslet.enableLeaderElection | quote }}
  METRICS_ADDR_CTRL_MGR: "0"
  METRICS_ADDR_SVC_MGR: {{ .Values.postgreslet.metricsAddr | quote }}
  PARTITION_ID: {{ .Values.postgreslet.partitionId | quote }}
  TENANT: {{ .Values.postgreslet.tenant | quote }}
kind: ConfigMap
metadata:
  name: {{ include "postgreslet.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "postgreslet.labels" . | nindent 4 }}
