apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: postgres-controller-controller-manager
  namespace: postgres-controller-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        controlplane-kubeconfig-hash:  {{ sha256sum .Values.controlplaneKubeconfig | trunc 63 | trimSuffix "-" }}
    spec:
      containers:
      - args:
        - --enable-leader-election=false
        - --partition-id=sample-partition
        - --tenant=sample-tenant
        command:
        - /manager
        image: r.metal-stack.io/extensions/postgreslet:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/run/secrets/postgreslet
          name: controlplane-kubeconfig
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: controlplane-kubeconfig
        secret:
          items:
          - key: controlplane-kubeconfig
            path: kube/config
          secretName: postgreslet
