apiVersion: v1
data:
  controlplane-kubeconfig: {{ b64enc .Values.controlplaneKubeconfig }}
kind: Secret
metadata:
  name: {{ include "postgreslet.fullname" . }}
  annotations:
    controlplane-kubeconfig-hash:  {{ sha256sum .Values.controlplaneKubeconfig | trunc 63 | trimSuffix "-" }}
