apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "postgreslet-support.roleNamePrefix" . }}-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "postgreslet-support.roleNamePrefix" . }}-readonly
subjects:
- kind: ServiceAccount
  name: {{ include "postgreslet-support.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}